version: '3'
services: 
  node:
    image: node:15.3.0
    volumes: 
      - ${PWD}:/opt/app
    working_dir: /opt/app
    ports:
      - 8080:8080
    command: "npm run serve"

networks:
  default:
    external:
      name: youtubeapi
